# Generated by Django 3.2.5 on 2021-07-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chainId', models.IntegerField()),
                ('symbol', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=300)),
                ('decimals', models.IntegerField(blank=True, null=True)),
                ('eip2612', models.BooleanField(blank=True, null=True)),
                ('address', models.TextField(blank=True, max_length=300, null=True)),
                ('logoURI', models.TextField(blank=True, null=True)),
                ('logo', models.TextField(blank=True, null=True)),
                ('decimal', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
